[FEATURE] Display network unavailable banner when no network connection is available
joshua-s/coronavirus-diary pull request #120
Opened 2020-03-24 23:10 UTC by bkonyi

Currently set to appear over every screen when network connection is lost. Once the user taps "CONTINUE OFFLINE", the banner will not be shown unless network connection is restored and then lost again. Banner disappears once network connection is restored.

**Screenshots:**
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-03-24 at 16 07 44](https://user-images.githubusercontent.com/24210656/77485173-b766da00-6de9-11ea-9234-4db5260ef1ee.png)

**---------------------------------------------------------------------------------------------------**

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-03-24 at 16 07 24](https://user-images.githubusercontent.com/24210656/77485170-b635ad00-6de9-11ea-8916-5105c46e056a.png)

**---------------------------------------------------------------------------------------------------**

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-03-24 at 16 07 01](https://user-images.githubusercontent.com/24210656/77485167-b3d35300-6de9-11ea-85d4-4fd1f7a9a34c.png)

2020-03-26 07:15 UTC, joshua-s commented on lib/src/ui/widgets/network_unavailable_banner.dart
> +  final Connectivity connectivity;
Nit: move this to the top of the class

2020-03-26 07:22 UTC, joshua-s commented on test/ui/widgets/network_connectivity_banner_test.dart
> +    testWidgets('and is dismissable', (tester) async {
This is super clean 👍

2020-03-26 07:27 UTC, ferndot submitted a review, later dismissed
This is great. Eventually, we might want to investigate a way to automatically wrap each screen with this. Perhaps, we could implement a custom scaffold.

2020-03-26 07:28 UTC, joshua-s commented
Please rebase this branch to remove the conflicts and then it can be merged!

2020-03-26 22:14 UTC, dnfield reviewed
@timsneath - is continue offline really an option for MVP?

2020-03-26 22:17 UTC, bkonyi commented on lib/src/ui/widgets/network_unavailable_banner.dart
> +  final Connectivity connectivity;
Done.

2020-03-26 22:17 UTC, bkonyi commented on test/ui/widgets/network_connectivity_banner_test.dart
> +    testWidgets('and is dismissable', (tester) async {
Thanks!

2020-03-26 22:19 UTC, bkonyi commented
> This is great. Eventually, we might want to investigate a way to automatically wrap each screen with this. Perhaps, we could implement a custom scaffold.

Yeah, I was thinking of doing a custom scaffold but wasn't sure if that's what we'd want at this point. Shouldn't be hard to do in the future if we decide to take that route.

2020-03-26 22:20 UTC, bkonyi commented
Ugh, rebased and got some other commits in here... I think this should still be good to go? @joshua-s

2020-03-26 23:36 UTC, dnfield commented on lib/src/ui/widgets/network_unavailable_banner.dart
> +                          ),
I don't think we should show this until there's actually offline capabilities, which is not being targetted for v1.

2020-03-26 23:37 UTC, dnfield requested changes
It doesn't make sense to let people continue offline if they cannot actually save any of this data anyway.

2020-03-27 00:05 UTC, bkonyi commented on lib/src/ui/widgets/network_unavailable_banner.dart
> +                          ),
I've added a `dismissible` property which defaults to false so we can re-enable this button later.

2020-03-27 00:06 UTC, bkonyi commented
> It doesn't make sense to let people continue offline if they cannot actually save any of this data anyway.

See the latest commits for the addition of a property which controls the visibility of the "CONTINUE OFFLINE" button.

2020-03-27 00:11 UTC, dnfield approved these changes
LGTM

2020-03-27 00:13 UTC, merged