Add location page, update questions
joshua-s/coronavirus-diary pull request #140
Opened 2020-03-28 02:40 UTC by gspencergoog

This adds a new location page that is part of the questions asked.

It switches between a location in the US, and a location in another country, validating inputs as much as it can.

As part of the update, I also modified all the questions to match the "canonical" list of questions in the doc, and eliminated `SimpleSlider`, since it's not used anymore.

Here's what it looks like:

![image](https://user-images.githubusercontent.com/8867023/77813014-90ffa380-7062-11ea-8963-1acbda2ab318.png)

![image](https://user-images.githubusercontent.com/8867023/77813026-a07eec80-7062-11ea-974c-7da9c9ac5584.png)

![image](https://user-images.githubusercontent.com/8867023/77813037-ac6aae80-7062-11ea-8643-ded310a584cb.png)

2020-03-28 05:08 UTC, joshua-s commented on lib/src/data/models/checkups.dart
>    String postalCode;
Since zip code is being used elsewhere, we could probably rename this too.

2020-03-28 05:10 UTC, joshua-s commented on lib/src/data/models/checkups.dart
>    String postalCode;
Could you rename this to "zip code" for consistency with the rest of the app? We can easily update the backend to match.

2020-03-29 07:48 UTC, joshua-s commented on lib/src/data/models/checkups.dart
> +      'CheckupLocation { postalCode: $zipCode, country: $country }';
```suggestion
      'CheckupLocation { zipCode: $zipCode, country: $country }';
```

2020-03-29 07:57 UTC, joshua-s commented
Eventually, it would be nice if the country input could be a searchable dropdown. Each item would be labeled with the country's full name and use the corresponding ISO 3166-1 alpha-2 code as its value.

Since this PR is already quite large, we could handle this in a follow-up PR if you prefer.

2020-03-29 18:00 UTC, gspencergoog commented
Yes, I agree it would give more reliable data to have a pulldown. I'll do that in another PR as soon as this is landed.

2020-03-29 18:01 UTC, gspencergoog commented on lib/src/data/models/checkups.dart
> +      'CheckupLocation { postalCode: $zipCode, country: $country }';
Fixed.

2020-03-30 04:35 UTC, ferndot requested changes
This is great 👍 ! There is one unused import that is breaking the tests. Once that is fixed, I think this is ready to go:
```
info • Unused import: 'package:covidnearme/src/ui/widgets/questions/inputs/entry_field.dart' • lib/src/ui/screens/checkup/steps/temperature.dart:1:8 • unused_import
```

One callout: some of the questions from the MVP questionnaire are not included. However, these can easily be added in a followup PR. I've added a list of these below for clarity.

Missing questions/questions that need changes:
- How high did your temperature get today?
- Have you been tested for flu, pneumonia, or other respiratory illness?
- Was the test positive?
- What did you have?
- Did you try to get tested for COVID-19?
- What was the result?
- Shortness of breath question should not have a subtitle.

2020-03-30 15:38 UTC, gspencergoog commented
OK, I fixed the extra import.  I'll add the other questions in another PR.

2020-03-30 18:25 UTC, ferndot approved these changes
LGTM!

2020-03-30 18:46 UTC, goderbauer commented
One issue I noticed when playing around with this PR: The keyboard doesn't get dismissed when you hit the next button after entering a ZIP code.

2020-03-30 18:51 UTC, merged