Replace Assessment screen with ThankYou screen
joshua-s/coronavirus-diary pull request #153
Opened 2020-03-30 22:01 UTC by goderbauer

Fixes https://github.com/coronavirus-diary/coronavirus-diary/issues/145.

2020-03-31 00:51 UTC, ferndot requested changes

2020-03-31 00:51 UTC, joshua-s commented on lib/src/ui/screens/checkup/checkup.dart
> +import 'package:covidnearme/src/ui/screens/thankyou/thankyou.dart';
Non-blocking: you could instead import the router here.
```suggestion
import 'package:covidnearme/src/ui/router.dart';
```

2020-03-31 00:51 UTC, joshua-s commented on lib/src/ui/screens/checkup/checkup.dart
>      PreferencesState preferencesState,
It looks like the preferences bloc is not needed anymore in this screen. Could you remove it please?

2020-03-31 00:51 UTC, joshua-s commented on lib/src/ui/screens/thankyou/thankyou.dart
> +import 'package:covidnearme/src/ui/widgets/network_unavailable_banner.dart';
Could you move this file into `screens/checkup`. It is a part of the Symptom Report (checkup) flow now.

2020-03-31 00:51 UTC, joshua-s commented on lib/src/ui/screens/thankyou/thankyou.dart
> +  static const routeName = '/thankyou';
Could this be nested under the Symptom Report route? I'm not sure whether snake or kebab case is more appropriate here.
```suggestion
  static const routeName = 'symptom-report/thankyou';
```

2020-03-31 01:43 UTC, joshua-s commented
#155 just landed and may require a few changes to this.

2020-04-01 21:21 UTC, joshua-s commented on lib/src/l10n/app_en.arb
> +  "checkupScreenHUDLabel": "Submitting your report",
We should replace `checkup`->`symptomReport` in a follow-up PR.

2020-04-01 21:25 UTC, joshua-s commented on lib/src/ui/screens/symptom_report/symptom_report.dart
> +    // TODO(goderbauer): Reset the SymptomsReport bloc.
https://github.com/coronavirus-diary/coronavirus-diary/issues/171

2020-04-01 21:29 UTC, goderbauer commented on lib/src/ui/screens/symptom_report/symptom_report.dart
> +    // TODO(goderbauer): Reset the SymptomsReport bloc.
Added a link to that bug.

2020-04-01 21:30 UTC, ferndot submitted a review, later dismissed
LGTM!

2020-04-01 21:30 UTC, goderbauer commented on lib/src/l10n/app_en.arb
> +  "checkupScreenHUDLabel": "Submitting your report",
Yeah, there are many other strings that still have the name checkup in them. Let's do that in a separate PR.

2020-04-01 21:41 UTC, joshua-s commented on lib/src/ui/screens/symptom_report/symptom_report.dart
> +    // TODO(goderbauer): Reset the SymptomsReport bloc.
👍

2020-04-01 21:42 UTC, joshua-s commented on lib/src/l10n/app_en.arb
> +  "checkupScreenHUDLabel": "Submitting your report",
Sounds good!

2020-04-01 23:07 UTC, goderbauer commented
@joshua-s I had to resolve another merge conflict, which dismissed your review. Can you approve again and possibly also submit to lower the chances of yet another merge conflict? Thanks!

2020-04-01 23:27 UTC, dnfield approved these changes

2020-04-01 23:28 UTC, merged