Intro screen UI changes
joshua-s/coronavirus-diary pull request #181
Opened 2020-04-02 11:28 UTC by aadarsh-patel

Closes #71 

Hey @joshua-s , 
Requesting for a code review.
And I also have a doubt,
Although the `title` has been changed "Welcome to the CovidNearMe App" to "Welcome to CovidNearMe". I left the semantics label of `title` unchanged to "Welcome to the Covid Near Me App".
I thought it would be more appropriate sentence for screen reader to read.
Is it fine or should i update semantic label for consistency?

#### Changes (All changes refers to Intro screen)
* Title changed from "Welcome to the CovidNearMe App" to "Welcome to CovidNearMe".
* Added a small description below the title.
* Button text changed from "LEARN MORE" to "GET STARTED".

#### Other changes due to above changes
* Updated app localizations.
* Updated tutorial_test, image_test, smoke_workflow_test and goldens.

#### .Screenshot of the changed UI
<img src="https://user-images.githubusercontent.com/53324291/78243008-a1030180-7500-11ea-81a2-09b5e3e849fb.png?raw=true"  align = "left" height = "350px">

2020-04-02 11:54 UTC, aadarsh-patel commented
I am trying to regenerate the internationalization code using command,
`dart tools/gen_l10n.dart --arb-dir lib/src/l10n`
But i am getting following error,
```fatal: Unexpected character
#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1394:5)
#1      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:847:56)
#2      _parseJson (dart:convert-patch/convert_patch.dart:31:10)
#3      JsonDecoder.convert (dart:convert/json.dart:495:36)
#4      JsonCodec.decode (dart:convert/json.dart:153:41)
#5      new AppResourceBundle (file:///C:/Users/Aadarsh/Desktop/tesla/coronavirus-diary/tools/gen_l10n_types.dart:369:14)
#6      LocalizationsGenerator.loadResources (file:///C:/Users/Aadarsh/Desktop/tesla/coronavirus-diary/tools/gen_l10n_lib.dart:534:46)
#7      main (file:///C:/Users/Aadarsh/Desktop/tesla/coronavirus-diary/tools/gen_l10n.dart:108:9)
<asynchronous suspension>
#8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

How can i solve this?

2020-04-03 07:35 UTC, joshua-s commented
@aadarsh-patel it was a good decision to leave the semantics as "Covid Near Me". Screen readers mispronounce "CovidNearMe"

2020-04-04 04:24 UTC, joshua-s commented on lib/src/l10n/app_en.arb
> +  "tutorialIntroStepDescription": "CovidNearMe is a US Centers for Disease Control project to help the public respond to the novel coronavirus (COVID-19). It allows you to:",
We don't have a current affiliation with the CDC. This is a potential alternative:
```suggestion
  "tutorialIntroStepDescription": "CovidNearMe lets you view statistics about COVID-19 in your local area and submit your symptoms to inform the disease response efforts.",
```

2020-04-04 04:24 UTC, joshua-s commented on lib/src/l10n/app_localizations_en.dart
> +      'CovidNearMe is a US Centers for Disease Control project to help the public respond to the novel coronavirus (COVID-19). It allows you to:';
Ditto from above.

2020-04-04 04:25 UTC, ferndot requested changes
Hey, thanks for working on this. It looks good, but needs a change to the description string.

2020-04-04 04:55 UTC, aadarsh-patel commented
Thanks for the review.
Happy to contribute!

2020-04-06 06:05 UTC, merged

2020-04-06 06:06 UTC, joshua-s commented
Merged, thanks @aadarsh-patel!