Handle network errors on symptom report submission
joshua-s/coronavirus-diary pull request #208
Opened 2020-04-15 20:25 UTC by bkonyi

If an exception is thrown while attempting to submit a symptom report, the symptom report widget will be rebuilt with questions pre-populated with the answers from the previous submission attempt. The last step of the symptom report will be shown after a network error, and an error snackbar will be displayed notifying the user that something went wrong.

Video [here](https://drive.google.com/open?id=1CQysdlamkcba7ApQn5PgQNe_6YyG_ucA).

2020-04-15 22:22 UTC, ferndot reviewed
Hey @bkonyi thanks for working on this--it got complicated really quickly. I have a few questions concerning the patterns used to implement this.

2020-04-15 22:22 UTC, joshua-s commented on lib/src/data/repositories/questions.dart
> +    List<QuestionResponse> currentResponses,
I am a bit wary of this pattern of modifying the questions at the repository level: the selected values seem more relevant to the UI.

Have you considered overriding [`QuestionView`](https://github.com/coronavirus-diary/coronavirus-diary/blob/031b600ebd5313fe10b82ae64622f716ddc21654/lib/src/ui/screens/symptom_report/steps/questions.dart#L77) to support a `symptomReport` parameter? This would be good for more than just this particular feature because it would enable two-way data binding for the symptom report.

Another option may be to hook into `buildWhen` on the `BlocConsumer` and prevent rebuilds for `SymptomReportStateNetworkError` and `SymptomReportStateCompleting`.

2020-04-15 22:22 UTC, joshua-s commented on lib/src/ui/screens/symptom_report/symptom_report.dart
> +  bool _showSnackbar = false;
Non-blocking nitpick: preference to include this at the top of the class with the other stateful variables

2020-04-15 22:22 UTC, joshua-s commented on test/blocs/symptom_report_test.dart
> +  test(
👍 thanks for adding the test!

2020-04-15 22:22 UTC, joshua-s commented on lib/src/ui/widgets/questions/question_view.dart
> +              // TODO(bkonyi): this value is always converted to F before being
Since the valid range of human temperatures is low and the difference between F and C temps is so large, the backend devs recently told me that we can submit both and they will automatically infer the appropriate unit. That should simplify this.

2020-04-16 16:49 UTC, bkonyi commented on lib/src/data/repositories/questions.dart
> +    List<QuestionResponse> currentResponses,
Yeah, that's fair, I wasn't sure where the best place to do this was and it seemed to work so I went with it haha. I'll take a look at `QuestionView` and see what I can do.

I looked into using `buildWhen` on the `BlocConsumer` before, but realized that changing the state of the HUD was enough to cause the `BlocConsumer` itself to be rebuilt. I could be missing something though as I'm still a bit of a Flutter amateur :-)

2020-04-16 16:50 UTC, bkonyi commented on lib/src/ui/screens/symptom_report/symptom_report.dart
> +  bool _showSnackbar = false;
Oh, of course. I probably dropped this here when I was trying something and forgot to move it. Will move in the next commit.

2020-04-16 16:50 UTC, bkonyi commented on test/blocs/symptom_report_test.dart
> +  test(
Of course!

2020-04-16 16:50 UTC, bkonyi commented on lib/src/ui/widgets/questions/question_view.dart
> +              // TODO(bkonyi): this value is always converted to F before being
Do we plan on dropping the conversion to F before submitting then? If that's the case, this won't be an issue at all.

2020-04-16 20:55 UTC, bkonyi commented on lib/src/data/repositories/questions.dart
> +    List<QuestionResponse> currentResponses,
Okay, I've moved this logic out of the questions repository; using `QuestionView` was much simpler!

2020-04-16 20:55 UTC, bkonyi commented
Should be ready for another review pass. Still need to fix the driver test since this messed something up there apparently...

2020-04-17 08:30 UTC, joshua-s commented on lib/src/ui/widgets/questions/question_view.dart
> +              // TODO(bkonyi): this value is always converted to F before being
Yeah, you can go ahead and drop the conversion.

2020-04-17 16:25 UTC, ferndot requested changes
Did another pass on this

2020-04-17 16:25 UTC, ferndot commented on lib/src/ui/screens/symptom_report/symptom_report.dart
> +        final steps = getSteps(
This causes a regression: on the first run when the informed consent is accepted, the combination of removing the informed consent step and navigating to the next step will actually skip the location step.

2020-04-17 16:25 UTC, ferndot commented on lib/src/ui/screens/symptom_report/symptom_report.dart
> +        final steps = getSteps(
Definitely open to a better solution for this issue that is less fragile than `if (steps.isEmpty)` if you have ideas.

2020-04-17 16:25 UTC, ferndot commented on lib/src/ui/widgets/questions/question_view.dart
> +          response.questionIdentifier: response,
I didn't know this syntax was possible in dart! 🆒 😎

2020-04-17 16:25 UTC, joshua-s commented on lib/src/blocs/questions/questions_event.dart
> +  final List<QuestionResponse> responses;
This can be removed since the responses are no longer stored in the questions state.

2020-04-17 16:25 UTC, joshua-s commented on lib/src/ui/screens/symptom_report/symptom_report.dart
> +        final steps = getSteps(
Perhaps, we could avoid changing the `getSteps()` function and instead pass the `_lastAttemptedReport` (and responses) down via a provider.

2020-04-17 17:05 UTC, bkonyi commented on lib/src/ui/screens/symptom_report/symptom_report.dart
> +        final steps = getSteps(
Ah yep, so that's why the driver test was failing. Thanks for pointing that out! I've moved to use a provider which is much more clean than trying to pass things around explicitly.

2020-04-17 17:08 UTC, bkonyi commented on lib/src/ui/widgets/questions/question_view.dart
> +          response.questionIdentifier: response,
Yep! For about a year now (since 2.3). This is one of the "UI as Code" features that were added with Flutter in mind ([here's an interesting blog post around these features](https://medium.com/dartlang/making-dart-a-better-language-for-ui-f1ccaf9f546c)).

2020-04-17 17:08 UTC, bkonyi commented on lib/src/blocs/questions/questions_event.dart
> +  final List<QuestionResponse> responses;
Whoops, thought I got this one. Done.

2020-04-17 23:29 UTC, joshua-s commented on lib/src/ui/widgets/questions/question_view.dart
> +          response.questionIdentifier: response,
Thanks for sending that post over. I must confess I'm thoroughly in love with Dart at this point 😍

2020-04-17 23:37 UTC, joshua-s commented on lib/src/ui/screens/symptom_report/symptom_report.dart
> +    List<SymptomReportStep> steps,
Nitpick: since steps is loaded in state, it does not need to be passed here.

2020-04-17 23:38 UTC, ferndot approved these changes
The recent change made this a lot cleaner, thank you! I think it is ready to merge.

One question:
1. Were you planning to remove the temperature conversion in this PR?

2020-04-20 16:19 UTC, bkonyi commented
> The recent change made this a lot cleaner, thank you! I think it is ready to merge.
> 
> One question:
> 
> 1. Were you planning to remove the temperature conversion in this PR?

Awesome! I'll remove that in another PR as it's not directly related to this change.

2020-04-20 16:20 UTC, merged