Show a screen asking the user for their zip code if needed
joshua-s/coronavirus-diary pull request #44
Opened 2020-03-23 01:53 UTC by Einarin

This adds another screen asking the user to entry their zip code. It is launched as part of the checkup flow if location services is unavailable or the user denies permission. Implements #6

2020-03-23 01:55 UTC, Einarin commented
I'm an experienced Android dev, but I've never used Flutter before, so let me know if I'm doing any of this wrong. Tested working on my Galaxy S9 running Android 10.

2020-03-23 01:57 UTC, bkonyi commented
Would you mind adding some screenshots?

2020-03-23 01:58 UTC, bkonyi commented on lib/src/ui/router.dart
> +import 'screens/get_zip_code/get_zip_code.dart';
You might want to sort your imports and exports alphabetically.

2020-03-23 01:59 UTC, bkonyi commented on lib/src/ui/screens/checkup/checkup_loaded_body.dart
> +      final GeolocationStatus permission = await geolocator.checkGeolocationPermissionStatus(locationPermission: GeolocationPermission.locationWhenInUse);
Can you run `dartfmt` (or `flutter format`) on your changes?

2020-03-23 02:00 UTC, bkonyi commented on lib/src/ui/screens/get_zip_code/get_zip_code.dart
> +                  "Please enter your zip code, or the zip code of the hospital you would go to, so that we can track the number of cases around specific hospitals."),
This should probably be broken up into multiple lines.

2020-03-23 02:02 UTC, bkonyi commented on lib/src/ui/screens/get_zip_code/get_zip_code.dart
> +            Container(
The contents of this container can all be `const`.

2020-03-23 02:03 UTC, bkonyi commented on lib/src/ui/screens/get_zip_code/get_zip_code.dart
> +                }),
Add trailing commas after the last argument for invocations that are longer than a single line. The formatter does nicer things when you do that :-).

2020-03-23 02:04 UTC, bkonyi commented on lib/src/ui/screens/get_zip_code/get_zip_code.dart
> +
Unnecessary whitespace.

2020-03-23 02:04 UTC, bkonyi commented on lib/src/ui/screens/get_zip_code/get_zip_code.dart
> +}
Should have a \n at the end of the file.

2020-03-23 02:05 UTC, bkonyi commented on lib/src/ui/screens/get_zip_code/get_zip_code.dart
> +        title: Text("Where Are You?")
I think that single quotes are preferred for this project, but I could be wrong.

2020-03-23 02:13 UTC, Einarin commented on lib/src/ui/screens/checkup/checkup_loaded_body.dart
> +      final GeolocationStatus permission = await geolocator.checkGeolocationPermissionStatus(locationPermission: GeolocationPermission.locationWhenInUse);
Done.

2020-03-23 02:48 UTC, Einarin commented on lib/src/ui/screens/get_zip_code/get_zip_code.dart
> +        title: Text("Where Are You?")
The codebase isn't consistent, I saw " strings in `home.dart`.  I did change these to all be ' strings.

2020-03-23 03:21 UTC, Einarin commented on lib/src/ui/screens/get_zip_code/get_zip_code.dart
> +            Container(
Oh interesting, `const` means compile time constant on values in dart. Changed.

2020-03-23 03:24 UTC, Einarin commented
As it turns out, `Geolocator.placemearkFromCoordinates()` is always throwing `PlatformException(ERROR_GEOCODING_COORDINATES, grpc failed, null)` on my device. I reworked `_saveCurrentLocation()` to always fall back to displaying this new UI if any part of geolocating fails.

2020-03-23 16:25 UTC, bkonyi commented on lib/src/ui/screens/get_zip_code/get_zip_code.dart
> +        title: Text("Where Are You?")
Ah, wasn't sure, but thanks for humoring me :-)

2020-03-23 17:19 UTC, bkonyi commented on lib/src/ui/screens/get_zip_code/get_zip_code.dart
> +  String _postalCode = null;
Everything is initialized to `null` by default in Dart, so you don't need to do this explicitly.

2020-03-23 17:19 UTC, bkonyi commented on lib/src/ui/screens/get_zip_code/get_zip_code.dart
> +      ]),
Nit: add a trailing comma after ']'

2020-03-23 17:19 UTC, bkonyi commented on lib/src/ui/screens/get_zip_code/get_zip_code.dart
> +        TextField(
We need some padding around this. I _think_ we've been using `EdgeInsets.all(40)` [elsewhere to pad similar views](https://github.com/coronavirus-diary/coronavirus-diary/blob/develop/lib/src/ui/screens/checkup/steps/temperature.dart#L150). @joshua-s can you confirm?

Layout should be similar to this: 

![image](https://user-images.githubusercontent.com/24210656/77343137-750ca280-6cee-11ea-9f1f-d7be736f1010.png)

2020-03-23 17:19 UTC, bkonyi commented on lib/src/ui/screens/checkup/checkup_loaded_body.dart
> +      print(e.toString());
Do we need this print? @joshua-s do we have any logging or do we plan on doing any?

2020-03-23 17:19 UTC, bkonyi commented on lib/src/ui/screens/get_zip_code/get_zip_code.dart
> +                  : () {
Nit: single line methods should use => notation if they're simple enough. e.g., `() => Navigator.of(context).pop(_postalCode)`.

2020-03-23 17:19 UTC, bkonyi commented on lib/src/ui/screens/checkup/checkup_loaded_body.dart
> +        final String postalCode = places[0].postalCode;
This is going to fall out of scope and is not needed since `postalCode` is declared above.

2020-03-23 17:19 UTC, bkonyi commented on lib/src/ui/screens/checkup/checkup_loaded_body.dart
> +    bool showLocationFallback = true;
Nit: I'd set this to false by default and set it to true in the catch clause.

2020-03-23 17:19 UTC, bkonyi commented on lib/src/ui/screens/checkup/checkup_loaded_body.dart
> +    } catch (e) {
Do we know the types of the exceptions that Geolocator can throw in the case where we're lacking permissions? If so, we should tighten up this catch clause to only catch those exceptions so we don't accidentally swallow an unexpected exception.

2020-03-23 18:20 UTC, joshua-s commented on lib/src/ui/screens/get_zip_code/get_zip_code.dart
> +        TextField(
Yes, that is correct. (side note: we should pull this into a theme eventually)

2020-03-23 18:24 UTC, joshua-s commented on lib/src/ui/screens/checkup/checkup_loaded_body.dart
> +      print(e.toString());
Currently, we do not have logging. We will need it eventually.

As far as this section is concerned. It would be good to fall back to the zip code prompt if geolocation throws an error.

2020-03-23 18:27 UTC, joshua-s commented on lib/src/ui/screens/checkup/checkup_loaded_body.dart
> +      print(e.toString());
As far as this logic is concerned, I'm not convinced that we will need to log this. What are your thoughts?

2020-03-23 18:35 UTC, bkonyi commented on lib/src/ui/screens/checkup/checkup_loaded_body.dart
> +      print(e.toString());
I don't think it's necessary as long as we only swallow the Geolocation exceptions.

2020-03-23 18:58 UTC, joshua-s commented on lib/src/ui/screens/checkup/checkup_loaded_body.dart
> +    } catch (e) {
It is looking like `PlatformException` is the main thing to catch here: https://github.com/Baseflow/flutter-geolocator/blob/ed70492e0d2f39efe4b4a9d345faa87bf7c620a6/lib/geolocator.dart#L215

2020-03-23 23:50 UTC, cyanglaz commented
Another alternative to this would be to use an [AlertDialog](https://api.flutter.dev/flutter/material/AlertDialog-class.html) (and [CupertinoDialog(https://api.flutter.dev/flutter/cupertino/CupertinoAlertDialog-class.html)]) to make it simplier.

2020-03-24 02:28 UTC, Einarin commented on lib/src/ui/screens/checkup/checkup_loaded_body.dart
> +        final String postalCode = places[0].postalCode;
Ah, that's a bug, I intended to set the one in the outer scope, missed that when I refactored this.

2020-03-24 02:31 UTC, Einarin commented on lib/src/ui/screens/checkup/checkup_loaded_body.dart
> +    bool showLocationFallback = true;
I did it this way on the basis that it'll run the fallback unless getting it succeeds. To do what you're proposing I'd also have to add an else to the the if and set it there also. This seemed clearer and less likely to be broken with changes.

2020-03-24 02:46 UTC, Einarin commented on lib/src/ui/screens/checkup/checkup_loaded_body.dart
> +    } catch (e) {
Note that that's not the only exception that can be thrown, at least you can also get `PlatformException(ERROR_GEOCODING_COORDINATES, grpc failed, null)` which is bubbling up from somewhere deeper. That's also a `PlatformException` that can be thrown when we have location permissions but can't resolve `Placemark`s. The docs for Geolocator unfortunately don't indicate what kinds of errors can occur.

I left it as a catch everything since that's what was there before, I don't love catching anything so I would definitely be on board to only catch `PlatformException` I was just concerned it might throw something else, and in this case since we have a fallback it seemed better not to crash over it. ¯\_(ツ)_/¯

2020-03-24 02:49 UTC, Einarin commented
> 
> 
> Another alternative to this would be to use an [AlertDialog](https://api.flutter.dev/flutter/material/AlertDialog-class.html) (and [CupertinoDialog](https://api.flutter.dev/flutter/cupertino/CupertinoAlertDialog-class.html) to make it simpler.

I started with that, and trying to make it have a text field and only enable the continue button based on the contents of that field I found it easier to make it a `StatefulWidget` and a separate screen. `AlertDialog` is also cancelled if you tap outside it, and I didn't feel like dealing with that complexity.

2020-03-24 02:57 UTC, Einarin commented on lib/src/ui/screens/get_zip_code/get_zip_code.dart
> +        TextField(
Updated layout:
![Screenshot_20200323-202425](https://user-images.githubusercontent.com/641166/77383554-dc574080-6d48-11ea-8854-ed3fc4321233.jpg)

2020-03-24 04:14 UTC, joshua-s commented on lib/src/ui/screens/checkup/checkup_loaded_body.dart
> +    } catch (e) {
That seems reasonable.

2020-03-24 04:15 UTC, joshua-s commented on lib/src/ui/screens/get_zip_code/get_zip_code.dart
> +                'you would go to, so that we can track the number of cases '
👍 good clarification here

2020-03-24 05:19 UTC, ferndot approved these changes
This is looking great. Thank you for implementing it @Einarin!

2020-03-24 05:21 UTC, ferndot requested changes
There are a few unused imports in this PR. Could you clean them up please and then we can merge.

```
   info • Unused import: 'package:path/path.dart' • lib/src/ui/router.dart:2:8 • unused_import
   info • Unused import: 'package:covidnearme/src/ui/assets/theme.dart' • lib/src/ui/screens/checkup/checkup_loaded_body.dart:1:8 • unused_import
   info • Unused import: 'package:flutter/services.dart' • lib/src/ui/screens/checkup/checkup_loaded_body.dart:3:8 • unused_import
   info • Unused import: 'package:covidnearme/src/ui/assets/theme.dart' • lib/src/ui/screens/get_zip_code/get_zip_code.dart:1:8 • unused_import
   info • Unused import: 'package:covidnearme/src/ui/utils/checkups.dart' • lib/src/ui/screens/get_zip_code/get_zip_code.dart:5:8 • unused_import
```

2020-04-03 07:45 UTC, joshua-s commented
Thank you for your work on this @Einarin. The project has been moving quite rapidly and this feature was covered in another PR. I am closing this now, please let me know if you have questions.

2020-04-03 07:45 UTC, closed without merging

2020-04-03 10:06 UTC, Einarin commented
Ah, sorry I didn't get back to this sooner! Life got in the way. Glad you got it covered 👍